#!/bin/sh

export DESTDIR=${PWD}/tmp
rm -rf $DESTDIR
mkdir $DESTDIR
export PATH=$DESTDIR/usr/local/bin:${PATH}
export LD_LIBRARY_PATH=$DESTDIR/usr/local/lib
export LPATH=$PWD/cvsnt/cvsapi:$PWD/cvsnt/cvstools:$DESTDIR/usr/local/lib
cd cvsnt
make distclean
./configure CC="aCC" CXX="aCC" CFLAGS="+O3 -Ae -mt" CXXFLAGS="+03 -AA -mt" LDFLAGS="-Wl,+b -Wl,/usr/local/lib" CPPFLAGS="-D_HPUX_SOURCE -D_POSIX_SOURCE -D__HP_NO_STRING_OVERLOADS -D_RWSTD_MULTI_THREAD -D_REENTRANT" --prefix=/usr/local --sysconfdir=/etc --disable-mdns
make DESTDIR=${DESTDIR}
make install DESTDIR=${DESTDIR}
cd ..
BUILD=`${DESTDIR}/usr/local/bin/cvsnt ver -q`
./make_package cvsnt $BUILD 32 
