#!/bin/bash

export PREFIX=/usr/local
export CONFIG=/etc/cvsnt
export CVSNT=${PWD}/cvsnt
export DESTDIR=${PWD}/tmp
export MYSQLDIR=${PWD}/../um_mysql32
rm -rf $DESTDIR
mkdir $DESTDIR
export LD_LIBRARY_PATH=${DESTDIR}${PREFIX}/lib:/usr/local/lib:/usr/local/ssl/lib
cd $CVSNT
make distclean
./configure --prefix=$PREFIX --with-config-dir=$CONFIG --with-ssl=/usr/local/ssl CFLAGS="-m32 -O2" CXXFLAGS="-m32 -O2" CPPFLAGS="-I/usr/local/include -I$MYSQLDIR/include/mysql" LDFLAGS="-L/usr/local/lib -L${PREFIX}/lib -R${PREFIX}/lib -L$MYSQLDIR/lib"
make DESTDIR=${DESTDIR}
make install DESTDIR=${DESTDIR}

cd ${DESTDIR}
BUILD=`${DESTDIR}${PREFIX}/bin/cvsnt version -q`
cp ../postinstall .
../make_package 32 ${BUILD} cvsnt
cd ..
