#!/bin/bash

export PREFIX=/usr/local
export CONFIG=/etc/cvsnt
export CVSNT=${PWD}/cvsnt
export TRIGGERS=${PWD}/triggers
export DESTDIR=${PWD}/tmp
export MYSQLDIR=${PWD}/../um_mysql32
rm -rf $DESTDIR
mkdir $DESTDIR
export LD_LIBRARY_PATH=${DESTDIR}${PREFIX}/lib:/usr/local/lib:/usr/local/ssl/lib
cd $CVSNT
make distclean
./configure --prefix=$PREFIX --with-config-dir=$CONFIG --with-ssl=/usr/local/ssl CFLAGS="-m32 -O2" CXXFLAGS="-m32 -O2" CPPFLAGS="-I/usr/local/include -I$MYSQLDIR/include/mysql" LDFLAGS="-L/usr/local/lib -L${PREFIX}/lib -R${PREFIX}/lib -L$MYSQLDIR/lib"
make DESTDIR=${DESTDIR}
make install DESTDIR=${DESTDIR}

cd $TRIGGERS
make distclean
./configure --with-cvsnt=$CVSNT --prefix=$PREFIX --with-config-dir=$CONFIG CFLAGS="-m32 -O2" CXXFLAGS="-m32 -O2" CPPFLAGS="-I${DESTDIR}${PREFIX}/include -I/usr/local/include -fPIC" LDFLAGS="-L${DESTDIR}${PREFIX}/lib -L${PREFIX}/lib -R${PREFIX}/lib"
make DESTDIR=$DESTDIR
make install DESTDIR=$DESTDIR

cd ${DESTDIR}
BUILD=`${DESTDIR}${PREFIX}/bin/cvsnt version -q`
cp ../postinstall .
cp $MYSQLDIR/lib/*.so.10* usr/local/lib
../make_package 32 ${BUILD} cvs-suite
cd ..
