//==============================================================;
//
//	This source code is only intended as a supplement to 
//  existing Microsoft documentation. 
//
// 
//
//
//  THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
//  KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
//  IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
//  PURPOSE.
//
//  Copyright (C) 1999 - 2001 Microsoft Corporation.  All Rights Reserved.
//
//
//
//==============================================================;

#include "ServerStatus.h"

// {F3E789B5-A191-4996-BCE4-E13815522FA5}
const GUID CServerStatus::thisGuid = { 0xf3e789b5, 0xa191, 0x4996, { 0xbc, 0xe4, 0xe1, 0x38, 0x15, 0x52, 0x2f, 0xa5 } };

//==============================================================
//
// CServerStatus implementation
//
//
